services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat
      POSTGRES_DB: chat
    ports: ["5432:5432"]
    volumes: ["pgdata:/var/lib/postgresql/data"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chat -d chat"]
      interval: 5s
      timeout: 5s
      retries: 5

  test_db:
    image: postgres:16
    environment:
      POSTGRES_USER: chat_test
      POSTGRES_PASSWORD: chat_test
      POSTGRES_DB: chat_test
    ports: ["5433:5432"]
    tmpfs:
        /var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build: .
    ports: ["8000:8000"]
    env_file: .env
    # قبل از اجرا، مایگریشن‌ها را خودکار بزن، بعد سرور را بالا بیاور
    command: >
      sh -c "uv run alembic upgrade head &&
             uv run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    # مقادیری که داخل شبکه‌ی داکر باید فرق کنند را override می‌کنیم
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql+asyncpg://chat:chat@db:5432/chat
      MINIO_ENDPOINT: minio:9000
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_started

volumes:
  pgdata:
  minio_data: