"""add canonical private conversation pair

Revision ID: 24385a70f07a
Revises: 1dfb81d0a4ac
Create Date: 2026-08-11 19:28:34.323542

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '24385a70f07a'
down_revision: str | Sequence[str] | None = '1dfb81d0a4ac'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('user_a_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('user_b_id', sa.Integer(), nullable=True))
    op.create_unique_constraint('uq_conversations_private_pair', 'conversations', ['user_a_id', 'user_b_id'])
    op.create_foreign_key(None, 'conversations', 'users', ['user_b_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'conversations', 'users', ['user_a_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_constraint('uq_conversations_private_pair', 'conversations', type_='unique')
    op.drop_column('conversations', 'user_b_id')
    op.drop_column('conversations', 'user_a_id')
    # ### end Alembic commands ###
